# -*- coding: utf-8 -*-
# 
#  plugin_api.py
#  kanji_test
#  
#  Created by Lars Yencken on 2008-10-24.
#  Copyright 2008 Lars Yencken. All rights reserved.
# 

class UserModelPlugin(object):
    """
    A plugin which provides one or more prior distributions across a form
    of user error.
    """
    
    def provides_dists(self):
        """
        Returns a list of tags as strings, where each tag is the name
        of an error distribution generated by this plugin.
        """
        raise Exception('not implemented')
    
    def build_dists(self, force=False):
        """
        Builds the prior distributions that this error model provides.
        """
        raise Exception('not implemented')